# Generated by Django 2.0.13 on 2019-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portfolio_site',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics'),
        ),
    ]
