# Generated by Django 2.0.13 on 2019-07-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20190711_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portfolio_site',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics'),
        ),
    ]
