# Generated by Django 2.0.13 on 2019-07-11 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_auto_20190711_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
